server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;

        # React routing fix (CRITICAL)
        try_files $uri $uri/ /index.html;
    }

    # Optional: cache static files
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}